#pragma once

enum ScreenModeFlag {
	SCREEN_WINDOW,
	SCREEN_WINDOW_MAXIMIZED,
	SCREEN_FULLSCREEN_DESKTOP,
	SCREEN_FULLSCREEN,
	SCREEN_NUMWINDOWTYPES,
	SCREEN_WINDOWTYPE_MASK = 0x3,
	SCREEN_DETAIL_MASK = 0x4,
	SCREEN_DISPLAYMODE_SHIFT = 3
};

#define SCREEN_GETDISPLAYMODE(screenMode) (((screenMode) >> SCREEN_DISPLAYMODE_SHIFT) & 0x1FFFFFFF)
