#pragma once

enum ScreenModeFlag {
	SCREEN_WINDOW,
	SCREEN_WINDOW_MAXIMIZED,
	SCREEN_FULLSCREEN_DESKTOP,
	SCREEN_FULLSCREEN,
	SCREEN_NUMWINDOWTYPES,
	SCREEN_WINDOWTYPE_MASK = 0x3,
	SCREEN_DETAIL_MASK = 0x4,
	SCREEN_VSYNC_MASK = 0x8,
	SCREEN_NOTDISPLAYMODE_MASK =
		SCREEN_WINDOWTYPE_MASK |
		SCREEN_DETAIL_MASK |
		SCREEN_VSYNC_MASK,
	SCREEN_DISPLAYMODE_SHIFT = 4
};

#define SCREEN_GETDISPLAYMODE(screenMode) (((screenMode) >> SCREEN_DISPLAYMODE_SHIFT) & 0x0FFFFFFF)
