#include "common.h"

const char* mission_name_editor[42] =
{
	"LEVEL STAR",
	"BIG",
	"DOUBLE",
	"TRIPLE",
	"HEBORIS",
	"CYCLE",
	"TARGET",
	"ERASER",
	"HI-SPEED1",
	"HI-SPEED2",
	"ANOTHER",
	"SINGLE",
	"X-RAY",
	"COLOR",
	"ROLL ROLL",
	"MIRROR",
	"T-SPIN",
	"ROTATELOCK",
	"HIDE NEXT",
	"DEVIL 800",
	"DEVIL 1200",
	"GARBAGE",
	"OLD STYLE",
	"ENDURANCE",
	"kn<> REVERSE",
	"BLIND",
	"ALL CLEAR",
	"COMBO",
	"BTOB 4L",
	"OOBAKA",
	"BLOCKORDER",
	"SINGLE ORDER",
	"DOUBLE ORDER",
	"RE TRIPLE ORDER",
	"SPLIT DOUBLE",
	"SPLIT TRIPLE",
	"SPLIT DOUBLE2",
	"T-SPIN DOUBLE",
	"TRIPLE ORDER",
	"ERASER HEBORIS",
	"SQUARE",
	"GOLD SQUARE",
};

const char* mission_name_jp[42] =
{
	"レベルスター",
	"ビッグ",
	"ダブル",
	"トリプル",
	"ヘボリス",
	"サイクル",
	"ターゲット",
	"イレイサー",
	"ハイスピード１",
	"ハイスピード２",
	"アナザー",
	"シングル",
	"X-RAY",
	"カラー",
	"ロールロール",
	"ミラー",
	"T-スピン",
	"回転不可",
	"NEXT不可視",
	"DEVIL 800",
	"DEVIL 1200",
	"GARBAGE",
	"オールドスタイル",
	"耐久",
	"上下左右逆転",
	"ブラインド",
	"全消し",
	"コンボ",
	"B to B ヘボリス",
	"OOBAKA",
	"ブロックオーダー",
	"シングルオーダー",
	"ダブルオーダー",
	"逆トリプルｵｰﾀﾞｰ",
	"中抜きダブル",
	"中抜きトリプル",
	"2段抜きダブル",
	"T-スピン ダブル",
	"トリプルオーダー",
	"イレイサーﾍﾎﾞﾘｽ",
	"スクウェア",
	"ゴールドｽｸｳｪｱ",
};

const char* mission_name_en[42] =
{
	"Level star",
	"Big",
	"Double",
	"Triple",
	"Heboris",
	"Cycle",
	"Target",
	"Eraser",
	"Hi-Speed 1",
	"Hi-Speed 2",
	"Another",
	"Single",
	"X-Ray",
	"Color",
	"Roll Roll",
	"Mirror",
	"T-spin",
	"Rotate Lock",
	"Hide NEXT",
	"DEVIL 800",
	"DEVIL 1200",
	"Garbage",
	"Old style",
	"Endurance",
	"Reverse Control",
	"Blind",
	"All Clear",
	"Combo",
	"B to B Heboris",
	"OOBAKA",
	"Block Order",
	"Single Order",
	"Double Order",
	"Re Triple Order",
	"Split Double",
	"Split Triple",
	"Split EX-Double",
	"T-Spin Double",
	"Triple Order",
	"Eraser Heboris",
	"Square",
	"Gold Square",
};

const char* mission_info_jp[42] =
{
	"%dライン消せ！",//0
	"%dライン消せ！",//1
	"%d回ダブルを決めろ！",
	"%d回トリプルを決めろ！",
	"%d回ヘボリスを決めろ！",
	"サイクルを決めろ！",
	"%dステージクリアしろ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",//10
	"%d回シングルを決めろ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"3コーナーの\nT-SPINで%d回\nラインを消せ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%dライン消せ！",//20
	"%dライン消せ！",
	"%dライン消せ！",
	"時間切れまで耐えろ！",
	"%dライン消せ！",
	"%dライン消せ！",
	"%d回全消しを決めろ！",
	"%dコンボを決めろ！",
	"%d回ヘボリスを決めろ！\n\nヘボリス以外で\nノルマがリセット！",
	"%dブロック置け！",
	"\n\nを使って\n%dライン消せ！",//30
	"\n\nを使って\n%d回シングルを決めろ！",
	"\n\nを使って\n%d回ダブルを決めろ！",
	"\n\n以外を使って\n%d回トリプルを決めろ！",
	"中抜きで%d回\nダブルを決めろ！",
	"中抜きで%d回\nトリプルを決めろ！",
	"2段抜きで%d回\nダブルを決めろ！",
	"3コーナーの\nT-SPINで%d回\nダブルを決めろ！",
	"\n\nを使って\n%d回トリプルを決めろ！",
	"ヘボリスで\n%dライン消せ！",
	"4x4の正方形を%d個作れ！",
	"1種類のブロックだけで\n4x4の正方形を%d個作れ！",
};

const char* mission_info_en[42] =
{
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase 2 lines at once\n%d time(s)!",
	"Erase 3 lines at once\n%d time(s)!",
	"Erase 4 lines at once\n%d time(s)!",
	"Do cycle!\n(all kinds of\n line erase)",
	"Clear %d stage(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase 1 line only\n%d time(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase the line by\n3-corner T-SPIN\n%d time(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Do not top out!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase all blocks\n%d time(s)!",
	"Do %d combo(s)!",
	"Erase 4 lines at once\n%d times!\n\nDo not erase\n3 or less lines!",
	"Put %d block(s)!",
	"Erase %d line(s)by\n\n\n         blocks!",
	"Erase 1 line only\n%d time(s)by\n\n\n         blocks!",
	"Erase 2 lines at once\n%d time(s)by\n\n\n         blocks!",
	"Erase 3 lines at once\n%d time(s)\nby other than\n\n\n         blocks!",
	"Erase 2 lines at once\nwith separated\nby one or two gap rows\n%d time(s)!",
	"Erase 3 lines at once\nwith separated\nby one gap row\n%d time(s)!",
	"Erase 2 lines at once\nwith separated\nby two gap rows\n%d time(s)!",
	"Erase 2 lines at once\nby 3-corner T-SPIN\n%d time(s)!",
	"Erase 3 lines at once\n%d time(s)\nby\n\n\n         blocks!",
	"Erase 4 lines at once\non the highlighted line\n%d time(s)!",
	"Make 4x4 square\n%d time(s)!",
	"Make 4x4 square\nby only 1 kind block\n%d time(s)!",

};
