#ifndef plane_h_
#define plane_h_

typedef enum PlaneNum
{
	PLANE_MEDAL,
	PLANE_HEBOFONT,
	PLANE_HEBOFLD,
	PLANE_HEBOSPR,

	PLANE_HEBOFLB1,
	PLANE_HEBOFLB2,
	PLANE_HEBOFLB3,

	PLANE_LOGO,
	PLANE_TITLE,
	PLANE_TEMP,

	PLANE_BACK01,
	PLANE_BACK02,
	PLANE_BACK03,
	PLANE_BACK04,
	PLANE_BACK05,
	PLANE_BACK06,
	PLANE_BACK07,
	PLANE_BACK08,
	PLANE_BACK09,
	PLANE_BACK10,
	PLANE_BACK11,
	PLANE_BACK12,

	PLANE_HEBOFONT4,
	PLANE_HEBOBTN,
	PLANE_HEBOFLB0,
	PLANE_TEXT,
	PLANE_GRADE,
	PLANE_MIRROR_EFFECT_TAP,
	PLANE_ITEM,
	PLANE_GUIDE,
	PLANE_UNUSED,
	PLANE_HEBOFONT3,

	PLANE_BREAK0,
	PLANE_BREAK1,
	PLANE_BREAK2,
	PLANE_BREAK3,
	PLANE_BREAK4,
	PLANE_BREAK5,
	PLANE_BREAK6,
	PLANE_BREAK7,

	PLANE_HEBOBLK0,
	PLANE_HEBOBLK1,
	PLANE_HEBOBLK2,
	PLANE_HEBOBLK3,

	PLANE_HEBORIS_ROAD,
	PLANE_DEL_FIELD,
	PLANE_HEBOBLK_SP,

	PLANE_HANABI_RED,
	PLANE_HANABI_ORANGE,
	PLANE_HANABI_YELLOW,
	PLANE_HANABI_GREEN,
	PLANE_HANABI_WATERBLUE,
	PLANE_HANABI_BLUE,
	PLANE_HANABI_PURPLE,

	PLANE_ITEM_GAUGE,
	PLANE_ROT,
	PLANE_MEDAL_TI,

	PLANE_PERASE1,
	PLANE_PERASE2,
	PLANE_PERASE3,
	PLANE_PERASE4,
	PLANE_PERASE5,
	PLANE_PERASE6,
	PLANE_PERASE7,

	PLANE_HEBOBLK0B,
	PLANE_SHOOTINGSTAR,

	PLANE_FLDMIRROR01,
	PLANE_FLDMIRROR02,
	PLANE_FLDMIRROR03,
	PLANE_FLDMIRROR04,

	PLANE_STAFFROLL,
	PLANE_BACK,
	PLANE_FADE,
	PLANE_HEBOBLK4_5,
	PLANE_HEBOBLK_OLD,
	PLANE_TOMOYO_EH_FADE,
	PLANE_HEBOBLK_BIG,
	PLANE_LINE,
	PLANE_LASER,
	PLANE_SHUFFLE_FIELD_EFFECT,
	PLANE_HEBOBLK6,
	PLANE_TEXT2,
	PLANE_ITEMERASE,
	PLANE_HEBOBLK_SP2,
	PLANE_ROTSTEXT,
	PLANE_HEBOFONT5,
	PLANE_GAMEMODEFONT,
	PLANE_ROLLMARK,
	PLANE_LOADING,
	PLANE_ITEMGRA,

	PLANE_COUNT
} PlaneNum;

#endif
