# This seems to be valid on Windows 10, at least.
# Update as necessary, if other system libraries get picked up.

install(CODE [[

set(PRE_EXCLUDES
"^api-ms-win"
)

set(POST_EXCLUDES
"system32"
)

file(GET_RUNTIME_DEPENDENCIES
	EXECUTABLES $<TARGET_FILE:HeborisC7EX-SDL2>
	PRE_EXCLUDE_REGEXES
		${PRE_EXCLUDES}
	POST_EXCLUDE_REGEXES
		${POST_EXCLUDES}
	RESOLVED_DEPENDENCIES_VAR RESOLVED_DEPENDENCIES
	UNRESOLVED_DEPENDENCIES_VAR UNRESOLVED_DEPENDENCIES
)
file(INSTALL
	DESTINATION ${CMAKE_INSTALL_PREFIX}
	TYPE SHARED_LIBRARY
	FOLLOW_SYMLINK_CHAIN
	FILES ${RESOLVED_DEPENDENCIES}
)

]])