#ifndef SYS_build_config_h_
#define SYS_build_config_h_

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define PROJECT_TITLE "@PROJECT_TITLE@"
#define PROJECT_CREATOR "@PROJECT_CREATOR@"
#define PROJECT_IDENTIFIER "@PROJECT_IDENTIFIER@"

#define SYS_PLATFORM "@SYS_PLATFORM@"

#define FILESYSTEM_ORG "@FILESYSTEM_ORG@"
#define FILESYSTEM_APP "@FILESYSTEM_APP@"
#define FILESYSTEM_CURRENT_DIRECTORY 0
#define FILESYSTEM_PORTABLE          1
#define FILESYSTEM_INSTALLABLE       2
#define FILESYSTEM_TYPE @FILESYSTEM_TYPE@
#define FILESYSTEM_BASE_PATH_APPEND "@FILESYSTEM_BASE_PATH_APPEND@"
#cmakedefine FILESYSTEM_USING_RESOURCE_DAT

#cmakedefine INPUT_ENABLE_LINUX_GPIO
#cmakedefine INPUT_ENABLE_KEYBOARD
#cmakedefine INPUT_ENABLE_GAME_CONTROLLER
#cmakedefine INPUT_ENABLE_GAME_CONTROLLER_DB
#cmakedefine INPUT_ENABLE_JOYSTICK
#cmakedefine INPUT_ONLY_DEVICE_TYPE @INPUT_ONLY_DEVICE_TYPE@
#cmakedefine INPUT_ONLY_GAME_CONTROLLER_TYPE @INPUT_ONLY_GAME_CONTROLLER_TYPE@
#cmakedefine INPUT_ONLY_SDL_CONTROLLER_TYPE @INPUT_ONLY_SDL_CONTROLLER_TYPE@
#define INPUT_JOY_KEY_ASSIGN_DEFAULT @INPUT_JOY_KEY_ASSIGN_DEFAULT@

#define VIDEO_SCREEN_MODE_BASE @VIDEO_SCREEN_MODE_BASE@
#define VIDEO_SCREEN_MODE_DEFAULT @VIDEO_SCREEN_MODE_DEFAULT@
#cmakedefine VIDEO_ENABLE_WINDOW_ICON_FILE
#cmakedefine VIDEO_ENABLE_ALL_SETTINGS

#cmakedefine GAME_ENABLE_QUIT

#endif
