/*
    * Don't Edit!! *  Created by Heboris2000 Setting Utility V1.60
    200
    208
    203
    205
    44
    45
    46
    72
    76
    75
    77
    79
    80
    81
[end]
*/

int		keyAssign[10 * 2] =
{
SDL_SCANCODE_UP, SDL_SCANCODE_DOWN, SDL_SCANCODE_LEFT, SDL_SCANCODE_RIGHT, SDL_SCANCODE_Z, SDL_SCANCODE_X, SDL_SCANCODE_C, SDL_SCANCODE_V, SDL_SCANCODE_Q, SDL_SCANCODE_W,
SDL_SCANCODE_KP_8, SDL_SCANCODE_KP_5, SDL_SCANCODE_KP_4, SDL_SCANCODE_KP_6, SDL_SCANCODE_KP_1, SDL_SCANCODE_KP_2, SDL_SCANCODE_KP_3, SDL_SCANCODE_KP_0, SDL_SCANCODE_PAGEUP, SDL_SCANCODE_PAGEDOWN,
};
