#include "include.h"

cstr mission_name_editor[42] =
{
	"LEVEL STAR",
	"BIG",
	"DOUBLE",
	"TRIPLE",
	"HEBORIS",
	"CYCLE",
	"TARGET",
	"ERASER",
	"HI-SPEED1",
	"HI-SPEED2",
	"ANOTHER",
	"SINGLE",
	"X-RAY",
	"COLOR",
	"ROLL ROLL",
	"MIRROR",
	"T-SPIN",
	"ROTATELOCK",
	"HIDE NEXT",
	"DEVIL 800",
	"DEVIL 1200",
	"GARBAGE",
	"OLD STYLE",
	"ENDURANCE",
	"kn<> REVERSE",
	"BLIND",
	"ALL CLEAR",
	"COMBO",
	"BTOB 4L",
	"OOBAKA",
	"BLOCKORDER",
	"SINGLE ORDER",
	"DOUBLE ORDER",
	"RE TRIPLE ORDER",
	"SPLIT DOUBLE",
	"SPLIT TRIPLE",
	"SPLIT DOUBLE2",
	"T-SPIN DOUBLE",
	"TRIPLE ORDER",
	"ERASER HEBORIS",
	"SQUARE",
	"GOLD SQUARE",
};

cstr mission_name_jp[42] =
{
	"���x���X�^�[",
	"�r�b�O",
	"�_�u��",
	"�g���v��",
	"�w�{���X",
	"�T�C�N��",
	"�^�[�Q�b�g",
	"�C���C�T�[",
	"�n�C�X�s�[�h�P",
	"�n�C�X�s�[�h�Q",
	"�A�i�U�[",
	"�V���O��",
	"X-RAY",
	"�J���[",
	"���[�����[��",
	"�~���[",
	"T-�X�s��",
	"��]�s��",
	"NEXT�s��",
	"DEVIL 800",
	"DEVIL 1200",
	"GARBAGE",
	"�I�[���h�X�^�C��",
	"�ϋv",
	"�㉺���E�t�]",
	"�u���C���h",
	"�S����",
	"�R���{",
	"B to B �w�{���X",
	"OOBAKA",
	"�u���b�N�I�[�_�[",
	"�V���O���I�[�_�[",
	"�_�u���I�[�_�[",
	"�t�g���v�����ް",
	"�������_�u��",
	"�������g���v��",
	"2�i�����_�u��",
	"T-�X�s�� �_�u��",
	"�g���v���I�[�_�[",
	"�C���C�T�[���ؽ",
	"�X�N�E�F�A",
	"�S�[���h�����",
};

cstr mission_name_en[42] =
{
	"Level star",
	"Big",
	"Double",
	"Triple",
	"Heboris",
	"Cycle",
	"Target",
	"Eraser",
	"Hi-Speed 1",
	"Hi-Speed 2",
	"Another",
	"Single",
	"X-Ray",
	"Color",
	"Roll Roll",
	"Mirror",
	"T-spin",
	"Rotate Lock",
	"Hide NEXT",
	"DEVIL 800",
	"DEVIL 1200",
	"Garbage",
	"Old style",
	"Endurance",
	"Reverse Control",
	"Blind",
	"All Clear",
	"Combo",
	"B to B Heboris",
	"OOBAKA",
	"Block Order",
	"Single Order",
	"Double Order",
	"Re Triple Order",
	"Split Double",
	"Split Triple",
	"Split EX-Double",
	"T-Spin Double",
	"Triple Order",
	"Eraser Heboris",
	"Square",
	"Gold Square",
};

cstr mission_info_jp[42] =
{
	"%d���C�������I",//0
	"%d���C�������I",//1
	"%d��_�u�������߂�I",
	"%d��g���v�������߂�I",
	"%d��w�{���X�����߂�I",
	"�T�C�N�������߂�I",
	"%d�X�e�[�W�N���A����I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",//10
	"%d��V���O�������߂�I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",
	"3�R�[�i�[��\nT-SPIN��%d��\n���C���������I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",
	"%d���C�������I",//20
	"%d���C�������I",
	"%d���C�������I",
	"���Ԑ؂�܂őς���I",
	"%d���C�������I",
	"%d���C�������I",
	"%d��S���������߂�I",
	"%d�R���{�����߂�I",
	"%d��w�{���X�����߂�I\n\n�w�{���X�ȊO��\n�m���}�����Z�b�g�I",
	"%d�u���b�N�u���I",
	"\n\n���g����\n%d���C�������I",//30
	"\n\n���g����\n%d��V���O�������߂�I",
	"\n\n���g����\n%d��_�u�������߂�I",
	"\n\n�ȊO���g����\n%d��g���v�������߂�I",
	"��������%d��\n�_�u�������߂�I",
	"��������%d��\n�g���v�������߂�I",
	"2�i������%d��\n�_�u�������߂�I",
	"3�R�[�i�[��\nT-SPIN��%d��\n�_�u�������߂�I",
	"\n\n���g����\n%d��g���v�������߂�I",
	"�w�{���X��\n%d���C�������I",
	"4x4�̐����`��%d���I",
	"1��ނ̃u���b�N������\n4x4�̐����`��%d���I",
};

cstr mission_info_en[42] =
{
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase 2 lines at once\n%d time(s)!",
	"Erase 3 lines at once\n%d time(s)!",
	"Erase 4 lines at once\n%d time(s)!",
	"Do cycle!\n(all kinds of\n line erase)",
	"Clear %d stage(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase 1 line only\n%d time(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase the line by\n3-corner T-SPIN\n%d time(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Do not top out!",
	"Erase %d line(s)!",
	"Erase %d line(s)!",
	"Erase all blocks\n%d time(s)!",
	"Do %d combo(s)!",
	"Erase 4 lines at once\n%d times!\n\nDo not erase\n3 or less lines!",
	"Put %d block(s)!",
	"Erase %d line(s)by\n\n\n         blocks!",
	"Erase 1 line only\n%d time(s)by\n\n\n         blocks!",
	"Erase 2 lines at once\n%d time(s)by\n\n\n         blocks!",
	"Erase 3 lines at once\n%d time(s)\nby other than\n\n\n         blocks!",
	"Erase 2 lines at once\nwith separated\nby one or two gap rows\n%d time(s)!",
	"Erase 3 lines at once\nwith separated\nby one gap row\n%d time(s)!",
	"Erase 2 lines at once\nwith separated\nby two gap rows\n%d time(s)!",
	"Erase 2 lines at once\nby 3-corner T-SPIN\n%d time(s)!",
	"Erase 3 lines at once\n%d time(s)\nby\n\n\n         blocks!",
	"Erase 4 lines at once\non the highlighted line\n%d time(s)!",
	"Make 4x4 square\n%d time(s)!",
	"Make 4x4 square\nby only 1 kind block\n%d time(s)!",

};
