#ifndef APP_build_config_h_
#define APP_build_config_h_

#define APP_PROJECT_VERSION "@APP_PROJECT_VERSION@"
#define APP_PROJECT_CREATOR "@APP_PROJECT_CREATOR@"
#define APP_PROJECT_NAME "@APP_PROJECT_NAME@"

#define APP_FILESYSTEM_ORG "@APP_FILESYSTEM_ORG@"
#define APP_FILESYSTEM_APP "@APP_FILESYSTEM_APP@"
#define APP_FILESYSTEM_CURRENT_DIRECTORY  0
#define APP_FILESYSTEM_PORTABLE    1
#define APP_FILESYSTEM_INSTALLABLE 2
#define APP_FILESYSTEM_TYPE        @APP_FILESYSTEM_TYPE@

#define APP_BASE_PATH_APPEND "@APP_BASE_PATH_APPEND@"

#cmakedefine APP_ENABLE_LINUX_GPIO_INPUT
#cmakedefine APP_ENABLE_KEYBOARD_INPUT
#cmakedefine APP_ENABLE_GAME_CONTROLLER_INPUT
#cmakedefine APP_ENABLE_GAME_CONTROLLER_DB_FILE
#cmakedefine APP_ENABLE_JOYSTICK_INPUT

#cmakedefine APP_ONLY_INPUT_TYPE @APP_ONLY_INPUT_TYPE@
#cmakedefine APP_ONLY_CONTROLLER_TYPE @APP_ONLY_CONTROLLER_TYPE@
#cmakedefine APP_ONLY_SDL_CONTROLLER_TYPE @APP_ONLY_SDL_CONTROLLER_TYPE@

#define APP_DEFAULT_JOYKEY_ASSIGN @APP_DEFAULT_JOYKEY_ASSIGN@

#define APP_BASE_SCREEN_MODE @APP_BASE_SCREEN_MODE@
#define APP_DEFAULT_SCREEN_MODE @APP_DEFAULT_SCREEN_MODE@

#define APP_FRAMEWORK_TYPE "@APP_FRAMEWORK_TYPE@"

#cmakedefine APP_ENABLE_ALL_VIDEO_SETTINGS

#cmakedefine APP_ENABLE_QUIT

#endif
