function(AddLibrariesVendor EXE LINK_PHYSFS)
	set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
	set(BUILD_SHARED_LIBS FALSE)

	set(SDL_SHARED FALSE)
	set(SDL_STATIC TRUE)
	set(SDL_TEST FALSE)
	set(SDL2_DISABLE_UNINSTALL ON)
	add_subdirectory("dep/SDL" "${CMAKE_BINARY_DIR}/dep/SDL")

	set(SDL2IMAGE_VENDORED ON)
	set(SDL2IMAGE_DEPS_SHARED OFF)
	set(SDL2IMAGE_SAMPLES OFF)
	set(SDL2IMAGE_INSTALL OFF)
	set(SDL2IMAGE_TESTS OFF)
	add_subdirectory("dep/SDL_image" "${CMAKE_BINARY_DIR}/dep/SDL_image")

	set(SDL2MIXER_VENDORED ON)
	set(SDL2MIXER_DEPS_SHARED OFF)
	set(SDL2MIXER_INSTALL OFF)
	set(SDL2MIXER_SAMPLES OFF)
	set(SDL2MIXER_VORBIS "VORBISFILE" CACHE STRING "Override")
	set(SDL2MIXER_VORBIS_VORBISFILE_SHARED OFF)
	set(SDL2MIXER_OPUS_SHARED OFF)
	add_subdirectory("dep/SDL_mixer" "${CMAKE_BINARY_DIR}/dep/SDL_mixer")

	if(TARGET SDL2::SDL2main)
		target_link_libraries("${EXE}" PUBLIC SDL2::SDL2main)
	endif()
	target_link_libraries("${EXE}" PUBLIC
		SDL2::SDL2-static
		SDL2_image::SDL2_image-static
		SDL2_mixer::SDL2_mixer-static
	)

	if(LINK_PHYSFS)
		set(CMAKE_POLICY_VERSION_MINIMUM "3.5")
		set(PHYSFS_BUILD_SHARED FALSE)
		set(PHYSFS_BUILD_STATIC TRUE)
		set(PHYSFS_BUILD_TEST FALSE)
		set(PHYSFS_BUILD_DOCS FALSE)
		set(PHYSFS_ARCHIVE_ZIP TRUE)
		set(PHYSFS_ARCHIVE_7Z FALSE)
		set(PHYSFS_ARCHIVE_GRP FALSE)
		set(PHYSFS_ARCHIVE_WAD FALSE)
		set(PHYSFS_ARCHIVE_HOG FALSE)
		set(PHYSFS_ARCHIVE_MVL FALSE)
		set(PHYSFS_ARCHIVE_QPAK FALSE)
		set(PHYSFS_ARCHIVE_SLB FALSE)
		set(PHYSFS_ARCHIVE_ISO9660 FALSE)
		set(PHYSFS_ARCHIVE_VDF FALSE)
		set(PHYSFS_DISABLE_INSTALL TRUE)
		add_subdirectory("dep/physfs" "${CMAKE_BINARY_DIR}/dep/physfs")
		target_link_libraries("${EXE}" PUBLIC
			PhysFS::PhysFS-static
		)
	endif()
endfunction()
